### ISSUE TITLE
Change tab background

### ISSUE THREAD

**Issue by aronzillo** [bluefirex/sublime-foculor#2]
Hello!, I made some changes to my favorite color scheme, but I would like to change the color of the tab when it is active (I want the same color as the inactive tabs) how could I solve it?

<img width="987" alt="captura de pantalla 2018-01-03 a la s 20 35 13" src="https://user-images.githubusercontent.com/12212275/34548169-24b1ee90-f0c6-11e7-961e-fdf2c0340a88.png">

**Comment by bluefirex** [comment]
Here's where to set the color for the active tab (=selected): https://github.com/bluefirex/sublime-foculor/blob/master/foculor.sublime-theme#L96
